default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  template: template0

development:
  <<: *default
  database: instagramapp_development

 
test:
  <<: *default
  database: instagramapp_test

production:
  <<: *default
  database: instagramapp_production
  username: instagramapp
  password: <%= ENV['INSTAGRAMAPP_DATABASE_PASSWORD'] %>
